### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by tschirmer** [mittwald/kube-httpcache#101]
**Is your feature request related to a problem? Please describe.**
ARM support for AWS gravtion2 processors

**Describe the solution you'd like**
should be able to be achieved within the build pipeline with the following:

```
docker buildx install
docker buildx create --use
docker buildx build --platform linux/amd64,linux/arm64 . -t quay.io/mittwald/kube-httpcache:v0.5.0 --push
```

**Describe alternatives you've considered**
Running different nodes and running kube-httpcache on a separate node group, this isn't ideal.

**Comment by martin-helmich** [comment]
@tschirmer I've just built `quay.io/mittwald/kube-httpcache:v0.6.0-alpha1` from the top of the #102 branch, but don't have an ARM machine at hand to test it. Mind giving it a go? 🙂
