### ISSUE TITLE
arm64 image is built with amd64 exporter

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/kube-httpcache#106]
This is a follow-up to #101.

The arm64v8 image is built with an amd64 build of the varnish-exporter binary, which is a bad idea for obvious reasons. 

Apparently, the upstream project does not release an amd64 build that we could just use out of the box, so we'll need to think of something. I remember we'd already discussed forking and building the exporter by ourselves in #81, so maybe that thought needs to be picked up again.

**Comment by gtirloni** [comment]
Was any agreement reached on this? If nobody is working on it, is it okay if I try?

**Comment by martin-helmich** [comment]
We're not using the ARM images ourselves, which is why this hasn't been a particularly high priority for us. The varnish-exporter project looks largely abandoned by now, but -- according to some discussion in the issues -- appears to be still compatible to Varnish 7.

With nearly two years of distance, forking the project seems unnecessary to me; however, there is still no ARM build, so maybe we could extend this (our) project's Dockerfile by another build stage for building the exporter from source, instead. Any contributions on this would be very welcome.
