### ISSUE TITLE
don't uninstall `apt-transport-https` in docker build

### ISSUE THREAD

**Issue by mattshin** [mittwald/kube-httpcache#107]
**Is your feature request related to a problem? Please describe.**
I cannot use this a pinned version of this docker image as a base image and use apt

Because the docker image uses the apt source `https://packagecloud.io/varnishcache/varnish60lts/debian/dists/stretch/InRelease`, we cannot run `apt update`:

```
$ apt update
...
Hit:4 http://deb.debian.org/debian stretch Release        
Get:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [722 kB]
Fetched 775 kB in 1s (575 kB/s)                          
Reading package lists... Done
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
E: Failed to fetch https://packagecloud.io/varnishcache/varnish60lts/debian/dists/stretch/InRelease  
```

This is probably fine as long as we are using the latest docker image (and the latest docker image is regularly updated with the most recent packages), but we would like to pin to an exact version for stability purposes. If the image is old enough, we cannot install `apt-transport-https` ourselves (using `apt`) because it is out-of-date.

**Describe the solution you'd like**
The docker image does not purge the `apt-transport-https`, allowing users to run `apt[-get] update` out-of-the-box without having to install packages from source.

We definitely understand purging build packages from the docker image, but in this case, it is definitely helpful to keep around and i think the 5mb package size is justified

**Additional context**
Luckily, `apt-update` _does_ update the `deb.debian.org` repos first, so we can technically run `apt-get update || true`, then update `apt-transport-https`, then proceed as normal, but this seems like a bit of a hack.

**Comment by hensur** [comment]
I've merge your PR
