### ISSUE TITLE
Mutli-pod HA deployments

### ISSUE THREAD

**Issue by tschirmer** [mittwald/kube-httpcache#11]
So I'm wanting to setup a HA varnish deployment, and have a single endpoint to send purge requests to: At the moment, as far as I can tell, we need to hit each pod replica in the varnish deployment.

e.g. 
```
Varnish Deployment:
-----------------
----Service ----
-----------------
  | |        \ \ 
----------  ----------
- Pod 1 -   - Pod 2 -
----------  ----------
 | |    \ \    / /   \ \
-------------------   ----------------------
----Backend 1 ---   ----- Backend 2 ----
-------------------   ----------------------
```

What I'm wanting to do is issue a PURGE request to a single endpoint and all pods then purge. At the moment, I'm only running a single varnish pod. 

We could use varnish broadcaster to achieve this; but we need to know the pod IP of each currently running pod, which would need to be updated on Deployment scale. 
https://docs.varnish-software.com/varnish-broadcaster/examples/

I'm thinking we could build out a second deployment that runs varnish broadcaster that updates it's nodes on change of the first deployment, with a Service that links into that. 

That setup would allow true HA (2 nodes of varnish running on 2 nodes, with 2 broadcasters running on 2 nodes ) If any 1 node destroyed, the service would remain up, with full capacity for purging.

**Comment by martin-helmich** [comment]
Thanks for the suggestion and sorry for the late response! Using Varnish Broadcaster sounds definitely feasible -- probably it would be possible to dynamically update its configuration with the currently running pod IPs of the Varnish cluster using a similar mechanism the varnish backends themselves are updated.

However, Varnish Broadcaster is part of Varnish Plus, which is not OSS, if I'm not mistaken? This might make deployment a little bit tricky. Also, I don't have access to any Varnish Plus components, to any input and/or contributions on this would be welcome.

**Comment by tschirmer** [comment]
That's true. Maybe we could build our own broacaster? it would essentially be a rely. wouldn't be too dofficult in golang. I'd be willing to help, just need to review what's in place now

**Comment by martin-helmich** [comment]
I agree that it shouldn't be too hard; basically just proxying a received HTTP request to multiple upstream servers.

There might be some overlap with #7, which also requires for the kube-httpcache controller to "know" about neighbouring Varnish pods belonging to the same Deployment.

Maybe we could extend this controller to not only watch its backend endpoints, but also additional varnish endpoints (also specified via `Service` name). These could then be exposed to the VCL template (solving #7) and the controller could also expose an additional HTTP endpoint that can be used as broadcaster.

What do you think?

**Comment by tschirmer** [comment]
That seems pretty good... kill 2 birds with one stone.

**Comment by RiFi2k** [comment]
I was looking at this for a solution. https://github.com/emgag/varnish-towncrier

**Comment by tschirmer** [comment]
@martin-helmich you still need help here? I'll have to have a look at the current controller and dig in a little.

**Comment by martin-helmich** [comment]
@tschirmer Sure, help is always welcome! :+1:

**Comment by dealancer** [comment]
@martin-helmich Please review the PR for this issue: https://github.com/mittwald/kube-httpcache/pull/19

**Comment by martin-helmich** [comment]
To anyone involved in this issue: #20, which implements a function similar to Varnish broadcaster, has now been merged and released. 🚀Many thanks to @dealancer for all your work on this feature! 👏
