### ISSUE TITLE
Occasional resets on v0.6.1

### ISSUE THREAD

**Issue by tschirmer** [mittwald/kube-httpcache#114]
**Describe the bug**

```
I1117 00:18:59.170253 1 endpoints_watch.go:73] endpoints did not change
W1117 00:19:18.867979 1 run.go:53] error while watching for updates: error while loading VCL (code 106): Message from C-compiler:
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Running C-compiler failed, exited with 4
VCL compilation failed
E1117 00:19:18.960014 1 run.go:84] signal broadcast error: Purge "http://10.100.102.107:6081/": read tcp 10.100.102.107:60068->10.100.102.107:6081: read: connection reset by peer
I1117 00:19:18.960033 1 run.go:85] retrying in 30s
Error: Child (31) not responding to CLI, killed it.
Error: Unexpected reply from ping: 400 CLI communication error (hdr)
Error: Child (31) died signal=9
Debug: Child cleanup complete
Debug: Child (282) Started
Info: Child (282) said Child starts
E1117 00:19:26.953294 1 run.go:84] signal broadcast error: Purge "http://10.100.97.79:6081/": read tcp 10.100.102.107:51126->10.100.97.79:6081: read: connection reset by peer
I1117 00:19:26.953309 1 run.go:85] retrying in 30s
```

**Expected behavior**
The varnish server to come up and stay up

**Environment:**
 - Kubernetes version: 1.19
 - kube-httpcache version: v0.6.1

**Configuration**
If applicable, add your VCL configuration file and other relevant configuration settings

**Additional context**

**Comment by LukeHandle** [comment]
Do you have inline C in the VCL? It seems to be complaining that the compilation is failing / it's a varnish config error which is causing the crash?

If you try with the built-in / default VCL, I assume it works okay?

If so, it would be relevent to post a minimum config that's causing the issue.

**Comment by martin-helmich** [comment]
The error indeed originates from the C compiler. I agree with @LukeHandle that any inline C snippets would be the first thing to look for; if there's no inline C in the VCL file, there'd have to be some other reason that GCC is killed (OOM, maybe? -- although this is all guesswork).

**Comment by tschirmer** [comment]
I was running around 128MB of RAM on the container. I'm not sure what the memory requirements for the compiler are, but if it needs more than that it would've been the issue.
