### ISSUE TITLE
Several vulnerabilities found with Trivy

### ISSUE THREAD

**Issue by ecniiv** [mittwald/kube-httpcache#119]
Hello,

According to Trivy scanner, there is several vulnerabilities found in the docker image, and some can be fixed with newer version of packages.

```
quay.io/mittwald/kube-httpcache:stable (debian 9.13)
====================================================
Total: 589 (UNKNOWN: 6, LOW: 29, MEDIUM: 290, HIGH: 229, CRITICAL: 35)
```

Is there any change to use newer version of golang and debian inside the Dockerfile to reduce as maximum as possible the number of CVE ?

Thanks,
ecniiv

**Comment by martin-helmich** [comment]
Apologies, this should not have been closed. Will investigate shortly.

**Comment by ecniiv** [comment]
Hi,

Did you investigate on these vulnerabilities ?
