### ISSUE TITLE
Wrong definition for service ports in README

### ISSUE THREAD

**Issue by mariuseliassen** [mittwald/kube-httpcache#127]
**Describe the bug**
The README.md in the repository has wrong port definitions for the cache-service.
It states that service should map port 80 to target port `80`, while it should in fact map port 80 to target port `8080`.

**To Reproduce**
Follow instructions in README.md to setup kubernetes using YAML files (not helm). Starting up the kubernetes cluster works fine, but accessing the service on port 80 results in `connection refused on pod <xxxx> port 80`.

**Expected behavior**
README.md should have correct examples

**Environment:**
 - Kubernetes version: any
 - kube-httpcache version: 0.6.1 / stable

**Configuration**
not relevant

**Additional context**
Not relevant

**Comment by martin-helmich** [comment]
Apologies, this should not have gotten stale. 🙏   Thanks for the report, the README indeed seems to be inaccurate.
