### ISSUE TITLE
Use current pod namespace as the default one

### ISSUE THREAD

**Issue by dealancer** [mittwald/kube-httpcache#13]
When the backend namespace is not set, but backend service is set there is an error message:

`an empty namespace may not be set when a resource name is provided`

In case if namespace is empty, it would be nice to set a namespace automatically to the one that Varnish pod is currently running in, this will make deployment config more reusable.

My use case is that I am using same deployment config for different environments (dev, stage, etc...) and even on demand environments created on the fly (which are associated with their own namespace).

**Comment by dealancer** [comment]
@martin-helmich 

This can be achieved with a following configuration:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: cache
        image: quay.io/spaces/kube-httpcache:stable
        imagePullPolicy: Always
        args:
        - -admin-addr=0.0.0.0
        - -admin-port=6083
        - -varnish-secret-file=/etc/varnish/k8s-secret/secret
        - -varnish-vcl-template=/etc/varnish/tmpl/default.vcl.tmpl
        - -varnish-storage=malloc,128M
        volumeMounts:
        - name: template
          mountPath: /etc/varnish/tmpl
        - name: secret
          mountPath: /etc/varnish/k8s-secret
      serviceAccountName: kube-httpcache  # when using RBAC
      volumes:
      - name: template
        configMap:
          name: vcl-template
      - name: secret
        secret:
          secretName: varnish-secret

**Comment by martin-helmich** [comment]
Thanks for the suggestion! :+1: I've updated the documentation accordingly.
