### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by dealancer** [mittwald/kube-httpcache#137]
What do you think of such logo?

https://smashinglogo.com/en/preview?s=b6z1gx8tz-5smhj6xac

**Comment by martin-helmich** [comment]
Sorry that this lay around a while. I'm not opposed to a snazzy logo per-se, but would prefer avoiding the plethora of copyright, licensing and trademark issues that go along with it, especially when using logo generators.

Apologies, but I think I'll close this for the time being.
