### ISSUE TITLE
Base Image debian:stretch is EOL 06/22

### ISSUE THREAD

**Issue by HuppertzL** [mittwald/kube-httpcache#156]
**Describe the bug**
The Image is based on `debian:stretch-slim`.
Stretch is EOL 06/22 and it seems like the package-repos for stretch will be shut off.

**To Reproduce**
Check the Dockerfile ;)

**Expected behavior**
`kube-httpcache`-Image running on `debian:bullseye-slim`

**Additional Information**
No Stretch anymore: http://security.debian.org/debian-security/dists/
No Stretch anymore: http://deb.debian.org/debian/dists/

**Comment by martin-helmich** [comment]
Fixed with https://github.com/mittwald/kube-httpcache/pull/155
