### ISSUE TITLE
Getting frequent rx timeouts - Backend Fetch Failed

### ISSUE THREAD

**Issue by sarasensible** [mittwald/kube-httpcache#157]
**Describe the bug**
Getting a high volume of rx timeouts.  Here is a comparison of the old (right) versus the new kube-httpcache (left)
<img width="1594" alt="Screen Shot 2023-05-17 at 5 37 10 PM" src="https://github.com/mittwald/kube-httpcache/assets/97973481/02460797-be26-47d9-96d7-8ab334f0f326">

I attempted resolving the issue by increasing the timeout_idle, first_byte_timeout and between_bytes_timeout but no joy.

I'm wondering if it might be related to the older version of varnish run by the kube-httpcache docker image.  The previous image we were running was 6.6.1 while the kube-httpcache is 6.0.11.

I acknowledge that this probably isn't a bug but more of a support request - feel free to guide me to more appropriate channels if that makes more sense.

**Environment:**
 - Kubernetes version: [e.g. 1.18] 1.25
 - kube-httpcache version: [e.g. v0.2.2] 0.7.2

**Configuration**
```
  vcl 4.0;

  import directors;
  import std;

  backend default {
    .host = "sensible-engine.weather.svc.cluster.local";
    .port = "8000";
    .first_byte_timeout = 600s;
    .between_bytes_timeout = 30s;
  }

  {{ range .Backends }}
  backend be-{{ .Name }} {
      .host = "{{ .Host }}";
      .port = "{{ .Port }}";
  }
  {{- end }}

  {{ range .Frontends }}
  backend {{ .Name }} {
      .host = "{{ .Host }}";
      .port = "{{ .Port }}";
  }
  {{- end }}

  sub vcl_init {
    new cluster = directors.shard();
    {{ range .Frontends -}}
    cluster.add_backend({{ .Name }});
    {{ end }}
    cluster.set_warmup(180);

    cluster.reconfigure();
    new lb = directors.round_robin();
    {{ range .Backends -}}
    lb.add_backend(be-{{ .Name }});
    {{ end }}
  }

  sub vcl_recv {

    set req.backend_hint = lb.backend();

    unset req.http.x-cache;
    set req.backend_hint = cluster.backend(by=URL);
    set req.http.x-shard = req.backend_hint;
    if (req.http.x-shard != server.identity) {
        return(pass);
    }
    set req.backend_hint = lb.backend();

    # always set hostname to the same k8 expected hostname
    set req.http.Host = "sensible-cache:8090";

    if (!req.url ~ "/api/v1") {
        return (pass);
    }

    /* TODO: replace with envvar based secret once VMODs is enabled */
    if (req.method == "PURGE") {
        if (! req.http.x-purge-control == std.getenv("PURGE_KEY")) {
          return(synth(405,"Not allowed."));
        }
        return (purge);
    }

    if (req.method != "GET" && req.method != "HEAD") {
          /* We only deal with GET and HEAD by default */
        return (pass);
    }


    /* rewrite lat, lon as latitude, longitude so we always cache */
    set req.http.url = regsub(
      req.url,
        "^lat=.*",
        "^latitude=.*"
    );

    set req.http.url = regsub(
      req.url,
        "^lon=.*",
        "^longitude=.*"
    );

    /* TODO: replace with basicauth VMOD once installed */
    if ( ! (req.http.Authorization == std.getenv("SENSIBLE_AUTH"))) {
      return(synth(401, "Restricted"));
    }

    return(hash);
  }

  sub vcl_backend_response {
    set beresp.ttl = 2s;

    if (bereq.url ~ "forecast/") {
      set beresp.ttl = 15m;
    }

    if (bereq.url ~ "observations/") {
      set beresp.ttl = 10m;
    }

    if (bereq.url ~ "ensemble-forecast/") {
      set beresp.ttl = 15m;
    }

    if (bereq.url ~ "(analysis|climatology|downscaled|activity)/") {
      set beresp.ttl = 70h;
      set beresp.grace = 2h;
    }

    if ( beresp.status >= 400 ) {
    set beresp.ttl = 0s;
      set beresp.grace = 0s;
    set beresp.uncacheable = true;
    }
  }

  sub vcl_deliver {
    if (obj.hits > 0) { # Add debug header to see if it's a HIT/MISS and the number of hits, disable when not needed
      set resp.http.X-Cache = "HIT";
    } else {
      set resp.http.X-Cache = "MISS";
    }
  }


  sub vcl_synth {
      set resp.http.Content-Type = "text/json";
      set resp.http.Retry-After = "5";
      synthetic( "{'message': '" +
                  resp.status + " " + resp.reason +
                  "'}"
      );
      return (deliver);
  }
```

Many thanks!

**Comment by sarasensible** [comment]
I found the Varnish discord channel and have gotten some great feedback.  I will record my learnings here for posterity.

It turns out that in Varnish 6.4 the idle timeout statistic was moved to rx_close_idle from rx_timeout https://github.com/varnishcache/varnish-cache/blob/8bfc5948c5031d4ca83a8ae200977d14fa5f0b75/doc/sphinx/whats-new/upgrading-6.4.rst#statistics so the difference I am seeing here is not actually an improvement in the Varnish 6.6 image -  it was the idle timeouts we were encountering were hidden in a different statistic.  So the underlying issue we are facing is the Varnish timing out on the backend going idle.

The behavior looks improved in Varnish 7.3 - my one takeaway is this repo might consider upgrading the underlying Varnish version, or at least building a separate Varnish 7 image.

This does not appear to be a bug related to kube-httpcache - in fact the feedback I have received leads me to think kube-httpcache is doing all the right things.  Thanks again for all the hard work on this repo!

**Comment by martin-helmich** [comment]
Hey Sara -- thanks for your analysis on this 👍; I've been meaning to have a look at this issue, but hadn't been able to find the time, yet. Bumping the bundled Varnish version is definitely something we should look into (although 6.0 is the LTS version and technically still supported, with 6.0.11 being the latest version). I've created #158 as a follow-up issue.
