### ISSUE TITLE
`docker build` setup is... strange?

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/kube-httpcache#21]
ATM, the docker images seem to be built *both*  by quay.io's automatic builds, *and* goreleaser in the Travis CI pipeline (with the latter one being [broken](https://travis-ci.org/github/mittwald/kube-httpcache/builds/663978282#L737)).

@Hermsi1337 since you were the last one to touch this, could you have a look when you find the time?

**Comment by Hermsi1337** [comment]
As far as I can tell, there actually is no `goreleaser` in this repository ^^.

IMHO we should also use `goreleaser` for `kube-httpcache` since we're using it in all our other repositories.

I will get into this tomorrow morning (=

**Comment by martin-helmich** [comment]
>As far as I can tell, there actually is no goreleaser in this repository ^^.

And you're absolutely right; seems I've assumed too much 🤦‍♂ -- it's a simple `docker build && docker push` combo. The problem stays the same, though.

**Comment by dealancer** [comment]
@martin-helmich, @Hermsi1337 is there a way we can have two Dockerfiles - one that relies on Gorelease and one that does not. Here is a use case: I build images by myself, I also use Tilt system for local development. Unfortunately Tilt only supports docker build command for building images:

```
docker_build(
  "kube-httpcache",
  "kube-httpcache",
  dockerfile="kube-httpcache/Dockerfile",
  ignore=[
    '.git',
    'README.md',
  ]
)
```

Another use case is building image from Docker compose. I am not very familiar with goreleaser, so I don't know if there are any workarounds, simply running `docker build` produces following error:

```
Step 7/8 : COPY        kube-httpcache /usr/bin/kube-httpcache
COPY failed: stat /var/lib/docker/tmp/docker-builder373320276/kube-httpcache: no such file or directory
```
