### ISSUE TITLE
Provide another Dockerfile to build image not using Gorelease.

### ISSUE THREAD

**Issue by dealancer** [mittwald/kube-httpcache#24]
Is there a way we can have two Dockerfiles - one that relies on Gorelease and one that does not. Here is a use case: I build images by myself, I also use [Tilt](https://tilt.dev) system for local development. Unfortunately Tilt only supports `docker build` command for building images and is not compatible with Gorelease:

```
docker_build(
  "kube-httpcache",
  "kube-httpcache",
  dockerfile="kube-httpcache/Dockerfile",
  ignore=[
    '.git',
    'README.md',
  ]
)
```

Another use case is building image from Docker compose.

I am not very familiar with Goreleaser, so I don't know if there are any workarounds, simply running `docker build` produces following error:

```
Step 7/8 : COPY        kube-httpcache /usr/bin/kube-httpcache
COPY failed: stat /var/lib/docker/tmp/docker-builder373320276/kube-httpcache: no such file or directory
```

_Originally posted by @dealancer in https://github.com/mittwald/kube-httpcache/issues/21#issuecomment-607940143_

**Comment by Hermsi1337** [comment]
I definitely did not think about this kind of use case.

The good thing about using a simple `COPY`-instruction inside the `Dockerfile` is, that we get the exact same binary in the released docker-image, as we would when downloading it from the [releases](https://github.com/mittwald/kube-httpcache/releases).



Without my first coffee there are only two solutions that come to my mind rapidly:
1. Use go-releaser inside the Dockerfile

**Comment by Hermsi1337** [comment]
I definitely did not think about this kind of use case.

The good thing about using a simple `COPY`-instruction inside the `Dockerfile` is, that we get the exact same binary in the released docker-image, as we would when downloading it from the [releases](https://github.com/mittwald/kube-httpcache/releases).

Without my first coffee there are only two solutions that come to my mind rapidly:
1. Use go-releaser inside a separate `Dockerfile`
2. Use a basic go-multistage-build in a separate `Dockerfile`

That way we would have two:
```
- Dockerfile
- Dockerfile.local (?)
```

**Comment by martin-helmich** [comment]
My two cents on this:

>Use go-releaser inside a separate Dockerfile
One issue might be that goreleaser does more for us than simply building the binary; it also determines which Docker images to build in the first place (and maybe at some point even do multi-architecture builds), and creates the Github releases.

How about doing this the other way around:

- A `Dockerfile` that does a simple multi-stage build without any external dependencies, and...
- ...a `Dockerfile.gorelease` that is used by goreleaser for our official releases?

That way an unsuspecting user could still simply clone this repo and run `docker build .` without any surprises.

**Comment by Hermsi1337** [comment]
I've prepared a PR containing the requested `Dockerfile`-change.

I did also take this as an opportunity to rebase this project in order to fit the [golang-standards](https://github.com/golang-standards/project-layout#go-directories).

What do you guys think?

**Comment by dealancer** [comment]
Good job, thanks!
