### ISSUE TITLE
Is it possible to share the memcache data between multiple pods to run Varnish in HA mode?

### ISSUE THREAD

**Issue by vickylance** [mittwald/kube-httpcache#245]
I want to run varnish in HA mode for horizontal scaling. But I want the cache to be persistent across the pods so that if the request goes to 1 varnish pod or the other it will be able to still serve the cache if its available. And the cache wont be on per pod level.
To achieve this is it possible to do it with memcache or some other backend storage?

**Comment by martin-helmich** [comment]
AFAIK this is not something that Varnish supports (see the list of supported storage backends in the [documentation](https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html)). To achieve redundancy, you'd need individual cache instances with independent (per-pod) storage backends.
