### ISSUE TITLE
Error Deploy statefulSet

### ISSUE THREAD

**Issue by ctit-cl** [mittwald/kube-httpcache#26]
Hi:

after creating the configmap and the secret, I have the following error when I want to display the StatefulSet

`[ValidationError(StatefulSet.spec.template.spec.containers[0]): unknown field "restartPolicy" in io.k8s.api.core.v1.Container, ValidationError(StatefulSet.spec.template.spec): unknown field "env" in io.k8s.api.core.v1.PodSpec, ValidationError(StatefulSet.spec): missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec]; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by martin-helmich** [comment]
Thanks for the report :+1: -- this is a documentation bug (the `restartPolicy` is a property of the Pod, not the Pod's container). Fix will follow shortly.
