### ISSUE TITLE
Image Scan Failed - Known Vulnerabilities to fix

### ISSUE THREAD

**Issue by tschirmer** [mittwald/kube-httpcache#29]
Hey,

I've just checked over the results for the vulnerability scan, and noticed that rpm and python have known vulnerabilities that are fixable.

![image](https://user-images.githubusercontent.com/3872130/85924807-de94e200-b8d7-11ea-9bdd-d22664a05dbf.png)

Any chance we can get some attention on this?

Thanks,
Tony

**Comment by martin-helmich** [comment]
Thanks for the report, @tschirmer. As of #31, the image will be built on the `debian:stretch-slim` image which should offer a much smaller attack surface than the old CentOS 7 base image (not that we'd even need Python or RPM for this project).
