### ISSUE TITLE
Purge request has not been distributed among all kube-httpcache pods in StatefulSet

### ISSUE THREAD

**Issue by voxmaster** [mittwald/kube-httpcache#41]
**Describe the bug**
Purge request has not been distributed among all kube-httpcache pods in StatefulSet. Only 2 pods in StatefulSet are receiving PURGE request and varnishlog is clean on others.

**To Reproduce**
1. Apply proposed configurations with VCL config for Magento2 (see "Configuration" section)
2. Scale kube-httpcache StatefulSet with more than 2 replicas: `kubectl scale sts cache-statefulset --replicas=4`
3. Configure Magento2 to communicate with `cache-service` Kubernetes Service 
4. Run `magento cache:flush` command to send purge request to kube-httpcache
5. Watch for `varnishlog` on each pod in StatefulSet

**Expected behavior**
All pods in k8s kube-httpcache StatefulSet should receive a Purge request  

**Environment:**
 - Kubernetes version: v1.14.10-gke.36
 - kube-httpcache version: v0.3.3

**Configuration**
VCL template: https://gist.github.com/voxmaster/26d45f370f55b49c9e589604ee82fc14     
Logs (pod logs and varnishlog output): https://gist.github.com/voxmaster/196479cca8c894792f1fe52728c03af0

**Comment by martin-helmich** [comment]
Are you using the correct port for sending your `PURGE` request? Please note that in the sample configuration, the actual HTTP proxy port and the signaller (which is used for broadcasting `PURGE` and `BAN` requests across the cluster) are running on different ports (80 and 8090, respectively).

**Comment by voxmaster** [comment]
@martin-helmich Thank you for a response! That was my bad.
`bin/magento setup:config:set --http-cache-hosts=cache-service:8090` does the trick and now all pods are receiving purge requests 🎉

**Comment by martin-helmich** [comment]
Thanks for the feedback. Happy to help. :tada:

**Comment by ggarcia1989** [comment]
hi @voxmaster First of all, thank you for this great job from kube http-cache.
 I'm experiencing problems clearing the cache of all varnish nodes from magento. In the log I see purge requests in all the varnish nodes, but when I start browsing the store, some pages are still cached.

I have configured magento env.php as you indicate in the comment to @ martin-helmich.

Could you give us a cable to solve it?



Thank you very much in advance.

**Comment by ggarcia1989** [comment]
@voxmaster @martin-helmich  
![image](https://user-images.githubusercontent.com/31269771/117314497-1de07780-ae87-11eb-8129-221c808c2fdb.png)

On the other hand, are the blocks indicated in the image necessary?

I can't understand the be-primary and fe-primary blocks.

Are they necessary for their correct operation?

Why does the backend block have a be - {{Name}} tag? Would this also be necessary?

Currently everything is working without those blocks, but cache clearing is failing in all vanish nodes since magento.

However, when I only have a pod of varnish everything works fine.

Thank you very much for your help, greetings.

**Comment by ggarcia1989** [comment]
When use this config i can see in log.
![image](https://user-images.githubusercontent.com/31269771/117316804-3a7daf00-ae89-11eb-8b4f-817033d14d52.png)
 Thanks!!

**Comment by ggarcia1989** [comment]
can someone help? With a single varnish pod everything works correctly, when scaling to 2,3 or 4 varnish pods and clearing cache from magento, the signaller probe is sent in the log but it does not clear the cache of all the varnish pods. Please help.

Does anyone have any indication that it might happen?

Thanks

**Comment by gustavo-lara-molina** [comment]
> When use this config i can see in log. ![image](https://user-images.githubusercontent.com/31269771/117316804-3a7daf00-ae89-11eb-8b4f-817033d14d52.png) Thanks!!

How do you resolve the issue with this VCC-compiler error? just commented that block?

**Comment by martin-helmich** [comment]
> I can't understand the be-primary and fe-primary blocks.
> 
> Are they necessary for their correct operation?

Only if you use them in your VCL config. In some cases (especially when you have stateful applications or applications that behave erratically when being scaled horizontally) it might be desirable to always direct traffic for certain URLs to one specific pod.

> How do you resolve the issue with this VCC-compiler error? just commented that block?

@ggarcia1989 @gustavo-lara-molina If you don't use that backend in your VCL config, you don't need to (or, to be more precise, "must not") define it.
