### ISSUE TITLE
Template Watcher only fired once

### ISSUE THREAD

**Issue by zorrofox** [mittwald/kube-httpcache#43]
**Describe the bug**
Template Watcher only fired once. I will change VCL template many time, but only fist template change will fired. And I can ensure this by see `kubectl logs StatefulSet/cache-statefulset`.

**To Reproduce**
1. Create a new Ctl;
2. Modify the ConfigMap of the VCL template once;
3. You can make sure that our modification has been applied by `kubectl logs`;
4. Modify the ConfigMap AGAIN, and apply the new ConfigMap;
5. You can make sure our ConfigMap has been modified by `cat /etc/varnish/tmpl/default.vcl.tmpl`;
6. And finally you will NEVER see any Watcher will fired by `kubectl logs`.

**Expected behavior**
We can apply any times of VCL template.

**Environment:**
 - Kubernetes version: 1.17.9
 - kube-httpcache version: v0.3.3

**Comment by martin-helmich** [comment]
By default, the controller uses inotify to watch for template updates. From experience I know this to be flaky in some cases (most often when reading from network filesystems, though). Can you try starting the controller with the `--varnish-vcl-template-poll` flag and see if the issue persists?

**Comment by zorrofox** [comment]
@martin-helmich ,

  Thanks! It's worked!
