### ISSUE TITLE
Pod Crashing

### ISSUE THREAD

**Issue by tschirmer** [mittwald/kube-httpcache#44]
**Describe the bug**
```
I1009 07:50:55.018020       1 watch.go:46] received new backend configuration: &{Endpoints:[{Name:application-deployment-756ccbd74d-56pbb Host:10.100.100.101 Port:80 Probe:<nil>} {Name:application-deployment-756ccbd74d-mjrg9 Host:10.100.102.89 Port:80 Probe:} {Name:application-deployment-756ccbd74d-72g7p Host:10.100.103.154 Port:80 Probe:} {Name:application-deployment-756ccbd74d-mc2ls Host:10.100.98.162 Port:80 Probe:} {Name:application-deployment-84f7849d6c-2kltp Host:10.100.99.187 Port:80 Probe:}] Primary:0xc000117680}
W1009 07:50:55.018361       1 run.go:53] error while watching for updates: context canceled
W1009 07:50:55.018673       1 run.go:53] error while watching for updates: context canceled
W1009 07:50:55.019120       1 run.go:53] error while watching for updates: context canceled
panic: signal: killed
goroutine 1 [running]:
main.main()
	/home/runner/work/kube-httpcache/kube-httpcache/cmd/kube-httpcache/main.go:149 +0xd12
```

**To Reproduce**
 add in liveness probe, restricted CPU to 100m, and memory to 128mib

**Expected behavior**

**Environment:**
 - Kubernetes version: 1.16
 - kube-httpcache version: v0.3.1

**Configuration**
If applicable, add your VCL configuration file and other relevant configuration settings

**Additional context**

**Comment by martin-helmich** [comment]
Sorry for the late response. Looking at the logs, is it possible that the Pod is actually being _killed_, maybe due to low memory? 128mib isn't a lot, and when running the deployment/statefulset from the README with the `malloc,128M` option, _definitely_ not sufficient.

**Comment by tschirmer** [comment]
This stopped once I added a little more RAM but I'll revisit this tomorrow. The OS shouldn't need much memory to run, I haven't done any profiling on this, but I'd imagine we could add an extra 32M to it and keep the malloc 128M? Or is that malloc something different to the C malloc? (I'm assuming it's going to allocate all 128MB to the cache on startup)

**Comment by tschirmer** [comment]
Just out of interest, this is a slightly different issue, but do you read the readiness state of the child pods when changing the config? or are they being added to the varnish config as soon as replica set is added to?

**Comment by martin-helmich** [comment]
>The OS shouldn't need much memory to run, I haven't done any profiling on this, but I'd imagine we could add an extra 32M to it and keep the malloc 128M?

I think that should work -- IIRC, Varnish will do either a simple `malloc` of the requested size on startup (or increase its allocation gradually up until that amount, I'm not entirely sure). But there's also a bit of overhead to consider for the Varnish process itself (binary, other dynamically allocated memory, libraries) and the `kube-httpcache` process.

**Comment by martin-helmich** [comment]
>Just out of interest, this is a slightly different issue, but do you read the readiness state of the child pods when changing the config? or are they being added to the varnish config as soon as replica set is added to?

Yes, indirectly. We read the service's endpoints, which are only published by Kubernetes if the respective Pods report as ready (which, on a side note, is the exact same behaviour that's causing #36).

**Comment by benjick** [comment]
I did a `kubectl rollout restart` and the pod gets stuck at `Terminating`, when I check the logs this is the error I see.

```
I1116 10:17:51.464359       1 main.go:143] received signal terminated
W1116 10:17:51.464424       1 run.go:53] error while watching for updates: context canceled
W1116 10:17:51.464430       1 run.go:53] error while watching for updates: context canceled
panic: signal: killed

goroutine 1 [running]:
main.main()
	/home/runner/work/kube-httpcache/kube-httpcache/cmd/kube-httpcache/main.go:149 +0xd12
```

**Comment by tschirmer** [comment]
I've also had this one. I'm still looking into any probes.
```
W1119 04:06:00.286557       1 run.go:53] error while watching for updates: EOF
panic: signal: killed
goroutine 1 [running]:
main.main()
	/home/runner/work/kube-httpcache/kube-httpcache/cmd/kube-httpcache/main.go:149 +0xd12
```

**Comment by benjick** [comment]
This shouldn't be closed, still seeing this issue, not only during rollouts

**Comment by cdaguerre** [comment]
@martin-helmich could this be re-opened?
