### ISSUE TITLE
Stateful set fails and cannot restart with frontend-watch enabled

### ISSUE THREAD

**Issue by tschirmer** [mittwald/kube-httpcache#48]
**Describe the bug**
When the pods within the stateful set fall to zero (due to a crash of nodes for instance), the stateful set cannot restart with frontend-watch enabled

**To Reproduce**
1. Create Stateful Set
2. set replicas to 2
3. delete all 2 pods
4. Stateful set stuck in not started state.

**Expected behavior**
Stateful set will be available if all pods get terminated.

**Environment:**
 - Kubernetes version:  1.17
 - kube-httpcache version: v0.3.4

**Configuration**
n/a

**Additional context**

```
I1126 00:49:40.914736       1 main.go:31] running kube-httpcache with following options: {Kubernetes:{Config: RetryBackoffString:30s RetryBackoff:30s} Frontend:{Address:0.0.0.0 Port:6081 Watch:true Namespace:staging Service: frontend-output PortName:http} Backend:{Watch:true Namespace:staging Service:app-no-cache Port: PortName:http} Signaller:{Enable:true Address:0.0.0.0 Port:8090 WorkersCount:1 MaxRetries:5 RetryBackoffString:30s RetryBackoff:30s} Admin:{Address:0.0.0.0 Port:6083} Varnish:{SecretFile:/etc/varnish/k8s-secret/secret Storage:malloc,128M AdditionalParameters: VCLTemplate:/etc/varnish/tmpl/default.vcl.tmpl VCLTemplatePoll:false} Readiness:{Enable:true Address:0.0.0.0:9102}}
I1126 00:49:40.914861       1 main.go:38] using in-cluster configuration
I1126 00:49:40.916198       1 run.go:15] waiting for initial configuration before starting Varnish
W1126 00:49:40.924043       1 endpoints_watch.go:50] service 'frontend-output' has no endpoints
I1126 00:50:37.989322       1 main.go:143] received signal terminated
```

**Comment by tschirmer** [comment]
This could be solved by adding a delay in the frontend watch code. 

A delay on startup that would allow varnish to start would solve this issue entirely.

**Comment by YannikBramkamp** [comment]
Thanks for the report! I tried to reproduce this issue but was not yet successful. 
What I did:
1. Create stateful set with two replicas
2. Delete pods with `kubectl get pods -n default --no-headers=true | awk '/cache/{print $1}'| xargs  kubectl delete -n default pod --grace-period=0 --force`
3. However, the pods proceeded to start and the stateful set became available

My log output:
```
I1208 15:01:02.173245       1 main.go:31] running kube-httpcache with following options: {Kubernetes:{Config: RetryBackoffString:30s RetryBackoff:30s} Frontend:{Address:0.0.0.0 Port:80 Watch:true Namespace:default Service:cache-service PortName:http} Backend:{Watch:true Namespace:default Service:nginx-service Port: PortName:http} Signaller:{Enable:true Address:0.0.0.0 Port:8090 WorkersCount:1 MaxRetries:5 RetryBackoffString:30s RetryBackoff:30s} Admin:{Address:0.0.0.0 Port:6083} Varnish:{SecretFile:/etc/varnish/k8s-secret/secret Storage:malloc,128M AdditionalParameters: VCLTemplate:/etc/varnish/tmpl/default.vcl.tmpl VCLTemplatePoll:false} Readiness:{Enable:true Address:0.0.0.0:9102}}
I1208 15:01:02.173344       1 main.go:38] using in-cluster configuration
I1208 15:01:02.176647       1 run.go:15] waiting for initial configuration before starting Varnish
W1208 15:01:02.185015       1 endpoints_watch.go:50] service 'cache-service' has no endpoints
I1208 15:01:02.581533       1 endpoints_watch.go:58] endpoints did not change
I1208 15:01:02.582885       1 run.go:35] creating initial VCL config
I1208 15:01:02.598415       1 wait.go:12] probing admin port until it is available
Warnings:
VCL compiled.

Debug: Version: varnish-6.0.7 revision 525d371e3ea0e0c38edd7baf0f80dc226560f26e
Debug: Platform: Linux,5.4.0-56-generic,x86_64,-junix,-smalloc,-sdefault,-hcritbit
Debug: Child (27) Started
Info: Child (27) said Child starts

```
If possible, could you share additional details on how to reproduce this issue?

**Comment by L3tum** [comment]
The issue here is if you define a readiness probe, which won't be successful, since kube-httpcache waits for Varnish and Kubernetes already expects it running (I THINK)

**Comment by L3tum** [comment]
Just confirmed it. With a readiness probe it hangs and eventually stops, but without any readiness probe it works flawlessly.

Maybe there could be another readiness probe? Running without one seems a bit...dangerous
