### ISSUE TITLE
VLC updated but not working

### ISSUE THREAD

**Issue by blackjid** [mittwald/kube-httpcache#56]
When I update the configmap with the vcl, I get the event log about the template being updated, thought the server is not using the new configuration.

This is the log, at the end there are some error I haven't being able to identify the cause.

```
main.go:31] running kube-httpcache with following options: {Kubernetes:{Config: RetryBackoffString:30s RetryBackoff:30s} Frontend:{Address:0.0.0.0 Port:80 Watch:true Namespace:services Service:kube-httpcache-headless PortName:http} Backend:{Watch:true Namespace:surbtc-staging Service:api Port: PortName:http} Signaller:{Enable:true Address:0.0.0.0 Port:8090 WorkersCount:1 MaxRetries:5 RetryBackoffString:30s RetryBackoff:30s} Admin:{Address:0.0.0.0 Port:6083} Varnish:{SecretFile:/etc/varnish/k8s-secret/secret Storage:malloc,128M AdditionalParameters: VCLTemplate:/etc/varnish/tmpl/default.vcl.tmpl VCLTemplatePoll:false} Readiness:{Enable:true Address:0.0.0.0:9102}}
main.go:38] using in-cluster configuration
run.go:15] waiting for initial configuration before starting Varnish
run.go:35] creating initial VCL config
wait.go:12] probing admin port until it is available
Warnings:
VCL compiled.
Debug: Version: varnish-6.0.7 revision 525d371e3ea0e0c38edd7baf0f80dc226560f26e
Debug: Platform: Linux,4.19.112+,x86_64,-junix,-smalloc,-sdefault,-hcritbit
Debug: Child (29) Started
Info: Child (29) said Child starts
dial.go:41] authentication required. challenge string: "pgsijtgprdlexoqsiivwqwpvwdjxbzdk"
wait.go:23] admin port is available
watch.go:35] received new frontend configuration: &{Endpoints:[{Name:varnish-kube-httpcache-0 Host:10.0.0.180 Port:80 Probe:<nil>} {Name:varnish-kube-httpcache-1 Host:10.0.2.217 Port:80 Probe:<nil>}] Primary:0xc000109580}
dial.go:41] authentication required. challenge string: "ioljpurbdczdxndgmdqybujfqptjbaiy"
endpoints_watch.go:58] endpoints did not change
endpoints_watch.go:58] endpoints did not change
endpoints_watch.go:58] endpoints did not change
endpoints_watch.go:58] endpoints did not change
watch.go:35] received new frontend configuration: &{Endpoints:[{Name:varnish-kube-httpcache-1 Host:10.0.2.217 Port:80 Probe:<nil>}] Primary:0xc000049fc0}
dial.go:41] authentication required. challenge string: "ahxktyozmzdprprgaaaocmmcvzjoztyb"
watch.go:35] received new frontend configuration: &{Endpoints:[{Name:varnish-kube-httpcache-0 Host:10.0.0.93 Port:80 Probe:<nil>} {Name:varnish-kube-httpcache-1 Host:10.0.2.217 Port:80 Probe:<nil>}] Primary:0xc000049fc0}
dial.go:41] authentication required. challenge string: "trcmjlnqogtgtigycxibpatjxerxvcim"
endpoints_watch.go:58] endpoints did not change
watch.go:22] VCL template was updated
dial.go:41] authentication required. challenge string: "cowyknlmtzwpggaevjsxqnlgvnkasxqe"
Security: CLI Authentication failure from telnet 127.0.0.1 37614 127.0.0.1 6083
watch.go:22] VCL template was updated
run.go:53] error while watching for updates: response code was 500, expected 200
dial.go:41] authentication required. challenge string: "jznsdmsaticwukxqqoenhcmhnttwcmca"
Security: CLI Authentication failure from telnet 127.0.0.1 37616 127.0.0.1 6083
run.go:53] error while watching for updates: response code was 500, expected 200
```

**Expected behavior**
I would expect that after the `VCL template was updated` logline the server should respond with the new configuration

**Environment:**
 - Kubernetes version: 1.15
 - kube-httpcache version: latest

**Comment by blackjid** [comment]
I have to try this, but maybe this is bacause of the autogenerated secret from the helm chart
https://github.com/mittwald/kube-httpcache/pull/51#discussion_r547112352

I'll try setting the secret from values

**Comment by martin-helmich** [comment]
@blackjid Sorry for the late reaction -- is this still current? From the looks of the log excerpt, it appears that this might indeed be an issue with the Varnish secret.

**Comment by blackjid** [comment]
This is still current, it's keeps happening... if I override the secret with a hardcoded one, it start working.
I added a option for the helm chart to use a custom secret.
#75

**Comment by SwitchTV-BenBettridge** [comment]
I think I found the cause for this issue - if you don't specify a static secret in the values file, then the secret is regenerated on each run of helm.

**Comment by HeWhoWas** [comment]
I've found the root cause of this issue: Mounted secrets are updated automatically. On the second deployment, the following happens:

1. Helm updates the secret as part of the deployment
2. Kubernetes updates the `/etc/varnish/k8s-secret/secret` value to have the new password
3. Kube-HTTPCache re-generates the varnish config
4. Kube-HTTPCache issues the reload request, referencing the `/etc/varnish/k8s-secret/secret` file (which contains the new password)
5. Reload fails.

I'm not sure the best solution - maybe copying the secret to another location on container startup, and comparing it **after** each reload to see if we need to update?

**Comment by robmoore** [comment]
Copying comment from PR #128 as this may be a better place for my question:

> I believe we have been seeing this issue in our environment. It doesn't appear that this change made it to 0.7.0. Is it possible it may be included in a release soon?
