### ISSUE TITLE
Varnish shared memory logging

### ISSUE THREAD

**Issue by znorris** [mittwald/kube-httpcache#8]
I'm currently working on a helm chart and ran into an issue with shared memory. I want to setup my helm chart with an additional pod that will run `varnishncsa` and write json logs to stdout. [To do so](https://varnish-cache.org/docs/trunk/reference/vsm.html) I need varnishd and varnishncsa to use the same working directory. This can be done by passing a flag, `-n`, at run-time.  I also need to set the `VSM_NOPID` env var in varnishncsa.

Since kube-httpcache is running varnishd it will have to pass that flag along. What are you thoughts on solving this?

1. My first thought was to add a flag and pass it to varnishd.
1. My second thought was to stop running varnishd from kube-httpcache and instead run both from the same pod. I'm assuming that the only requirement is that the two can communicate via the admin port. If that's correct I think that might be a better option. This way kube-httpcache doesn't have to get in the middle of everything.

**Comment by znorris** [comment]
For the sake of time, and my immediate need, I went ahead and implemented number one https://github.com/znorris/kube-httpcache/commit/1f86e1810fe8098772b41b9ba7ff96c24bf4aa7f.

**Comment by mqmr** [comment]
Hello,

I am also interested in having this functionality because my current varnish installation on k8s uses it.
@martin-helmich sorry for pinging you directly. Could you please tell if it would be possible to backport znorris's changes into the main project?

Thank you!
