### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by kamsz** [mittwald/kube-httpcache#84]
**Describe the bug**
kube-httpcache container is slowly eating memory. 2Gi memory limit is being eaten within 48 hours.

![image](https://user-images.githubusercontent.com/2961450/125409363-1d4eea80-e3bc-11eb-82c3-afa665cc65c3.png)

**To Reproduce**
Run kube-httpcache.

**Expected behavior**
Memory usage staying rather stable or at least not increasing steadily over time.

**Environment:**
 - Kubernetes version: 1.18
 - kube-httpcache version: latest master

**Configuration**
If that's necessary I can share VCL, but that's pretty much 90% regular Magento 2 VCL.

**Comment by martin-helmich** [comment]
Just to pin this down: How is the Varnish process itself configured (storage size and storage backend)? Also, is there way for you to determine if the memory consumption is caused by Varnish itself, or by the `kube-httpcache` controller process?

**Comment by kamsz** [comment]
@martin-helmich Hi! I'm currently trying to pin it down which component is eating the memory. I'll keep you updated.
